name: Super-Linter
#Event
on: push
#Jobs
jobs:
  super-lint:
    name: Lint code base
#Runner
    runs-on: ubuntu-latest
#Steps    
    steps:
     - name: Lint Action
#Actions
       uses: wearerequired/lint-action@v2.3.0
       env: 
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       
